#!/bin/sh

for a in . .. ../.. ; do [ -e $a/tests.sh ] && . $a/tests.sh ; done

NAME='dbg.aaa'
FILE=../../../bins/elf/true
ARGS='-A -d'
CMDS='dcu main
fd
afi main~?name: main
'
EXPECT='main
1
'
IGNORE_ERR=1
run_test